### PR TITLE
Exambook

### PR DESCRIPTION
**Pull request by micklwl**
I think the exam book is done. Need to work on putting it as a storage file and logic next.

### CODE REVIEW

**Comment by micklwl** [comment]
Creation of a new exams.txt and tests for the file is completed.
Working on CreateCommand next to add exam into exams.txt.

**Comment by micklwl** [comment]
This is the most I can do to reduce the extras at this page. The method that Codacy points out is exactly like another method in that same file, however the number of implementation is lower as there is no ability to access the file now.

**Comment by micklwl** [comment]
Coveralls decrease as exams is not used as its not printed on screen yet.

**Comment by 0WN463** [comment]
As requested by OP to close thread and continue on new PR. Closing

**Pull request closed without merging**
